---
abstract: 'Mail::Toaster perl programs and modules'
author:
  - 'Matt Simerson (matt@tnpi.net)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-Toaster
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 1
  Date::Parse: 1
  Email::Valid: 0
  IO::Socket::SSL: 0
  Mail::Ezmlm: 0
  Mail::Send: 0
  Net::DNS: 0.2
  Params::Validate: 0.7
  Test::Simple: 0
  URI: 0
  perl: 5.008001
  version: 0
version: 5.37
